### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by orielswisa** [JamesBremner/so76407006#1]
Actually it is not related directly to this project.
Inside the "wex.h" there is Create function that creates a managed window.
the runtime error that I get is this:
![image](https://github.com/JamesBremner/so76407006/assets/78354992/d17173eb-fa89-423b-81c9-9eee6045c794)

Again, thanks a lot for your help!

**Comment by JamesBremner** [comment]
Please provide the traceback so that I can see where this is being called from.

**Comment by JamesBremner** [comment]
It would also help if you posted the build log.  It should look like this

```
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/main.o ./src/main.cpp -I./include -I../windex/include -I../raven-set -I../../code_ext/boost/boost1_78
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/cellCombiner.o ./src/cellCombiner.cpp -I./include -I../windex/include -I../raven-set -I../../code_ext/boost/boost1_78     
g++ -g \
-o bin/starter.exe .vscode/obj/main.o .vscode/obj/cellCombiner.o  \
-static-libstdc++ -static-libgcc -static -lComctl32 -lgdiplus -lgdi32 -lcomdlg32 -lstdc++fs -L../../code_ext/boost/boost1_78/lib -lboost_system-mgw11-mt-x64-1_78 -lboost_program_options-mgw11-mt-x64-1_78
```

**Comment by orielswisa** [comment]
Unhandled exception at 0x757E8FC2 in CppProjectPolyomino.exe: Microsoft C++ exception: std::runtime_error at memory location 0x012FF18C.

![image](https://github.com/JamesBremner/so76407006/assets/78354992/ccd7b415-575c-4118-8d5f-bec93ec833ba)

**Comment by orielswisa** [comment]
Rebuild started...
1>------ Rebuild All started: Project: CppProjectPolyomino, Configuration: Debug Win32 ------
1>Source.cpp
1>C:\Repositories\GitHub\windex\include\wex.h(697,20): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\wex.h(698,20): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\wex.h(699,20): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\wex.h(700,20): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\wex.h(701,20): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\wex.h(702,20): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\wex.h(703,20): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\wex.h(704,20): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\wex.h(716,20): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\wex.h(1818,36): warning C4244: 'argument': conversion from 'LRESULT' to 'unsigned short', possible loss of data
1>C:\Repositories\GitHub\windex\include\slider.h(62,24): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\slider.h(111,30): warning C4244: 'argument': conversion from 'double' to 'unsigned short', possible loss of data
1>C:\Repositories\GitHub\windex\include\slider.h(172,24): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\slider.h(180,24): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\guage.h(43,19): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\guage.h(44,19): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\windex\include\guage.h(51,20): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
1>C:\Repositories\GitHub\PolyominoCreatorGithub\CppProjectPolyomino\CppProjectPolyomino\Source.cpp(170,19): warning C4018: '>=': signed/unsigned mismatch
1>C:\Repositories\GitHub\PolyominoCreatorGithub\CppProjectPolyomino\CppProjectPolyomino\Source.cpp(221,29): warning C4018: '<': signed/unsigned mismatch
1>C:\Repositories\GitHub\PolyominoCreatorGithub\CppProjectPolyomino\CppProjectPolyomino\Source.cpp(223,33): warning C4018: '<': signed/unsigned mismatch
1>C:\Repositories\GitHub\PolyominoCreatorGithub\CppProjectPolyomino\CppProjectPolyomino\Source.cpp(238,35): warning C4018: '<': signed/unsigned mismatch
1>C:\Repositories\GitHub\PolyominoCreatorGithub\CppProjectPolyomino\CppProjectPolyomino\Source.cpp(239,39): warning C4018: '<': signed/unsigned mismatch
1>CppProjectPolyomino.vcxproj -> C:\Repositories\GitHub\PolyominoCreatorGithub\CppProjectPolyomino\Debug\CppProjectPolyomino.exe
1>Done building project "CppProjectPolyomino.vcxproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

this is my build output on visual studio

**Comment by JamesBremner** [comment]
> this is my build output on visual studio

This project does not use the microsoft C++ compiler.  It uses the standard g++ compiler and mingw.

You should use the VSCODE project I supply.

**Comment by JamesBremner** [comment]
To simplify the build I have removed the boost dependency.  The build log should now look like:

```
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/main.o ./src/main.cpp -I./include -I../windex/include -I../raven-set
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/cellCombiner.o ./src/cellCombiner.cpp -I./include -I../windex/include -I../raven-set
g++ -g \
-o bin/starter.exe .vscode/obj/main.o .vscode/obj/cellCombiner.o  \
```

**Comment by JamesBremner** [comment]
Detailed build instructions are here https://github.com/JamesBremner/so76407006/wiki/Build-Instructions

**Comment by orielswisa** [comment]
ok, I'll try again.

**Comment by orielswisa** [comment]
where should I put the the build commands?
this is my first time on vscode with c++...

**Comment by JamesBremner** [comment]
Not sure what you mean by build commands

Have you followed the instructions in the wiki?  If so, then you press the F9 key to start the build.

**Comment by JamesBremner** [comment]
I have numbered the build instructions in the wiki.  Please let me know which step you are stuck on

**Comment by orielswisa** [comment]
I don't know why but for me it didn't work. Using the build log you mentioned above I created my own makefile and finally, it works. thanks for helping with it.
